HOST_IP = "localhost"
USER = "root"
PASSWORD = "9055259140"
GROUP_NAME = "GroupA"
DEVICE_ID = "DeviceA"

MQTT_HOSTNAME = "nam1.cloud.thethings.network"
MQTT_USERNAME = "4id3-data-collection@ttn"
MQTT_API_KEY = "NNSXS.7RKFCH2PAY4IM3JTNJIDHRFZ3QLXSTCPL2MR2TI.CMUAHXP3BG5LJ3C3HUNLOUHXLNMTBZJ3FLUOR2KG3IWNVC2MUTXQ"
MQTT_PORT = 1883
MQTT_TOPIC = "#"

